#!/bin/bash

case "$1" in
    1)
        java -jar $HOME/games/Minecraft.jar & disown
        ;;
    2)
        cd $HOME/games/ZeldaClassic/
        ./zelda-l & disown
        ;;
    3)
        cd $HOME/games/Katawa_Shoujo/
        ./Katawa\ Shoujo.sh & disown
        ;;
    4)
        cd $HOME/games/DDLC
        ./DDLC.sh & disown
        ;;
    *)
        clear
        echo "01 | Minecraft"
        echo "02 | Zelda Classic"
        echo "03 | Katawa Shoujo"
        echo "04 | Doki Doki Literature Club!"

        echo ""
        echo "e) Edit"
        echo "* Type anthing else to cancel *"
        echo ""
        printf 'Choose: '
        read -r option

        re='^[0-9]+$'

        if [ $option = "e" -o $option = "edit" ]; then
            edit $HOME/.bash_sources/games
        elif [[ $option =~ $re ]] ; then
            game $option
        fi
        ;;
esac

echo
