#!/bin/bash

linking() {
    if [ ! -e $2 ]; then
        ln -sf $1 $2
    fi
}

cd $(dirname $0)

# linking  $(pwd)/terminator_config  $HOME/.config/terminator/config

linking  $(pwd)/bash_profile       $HOME/.bash_profile
linking  $(pwd)/bash_sources       $HOME/.bash_sources
linking  $(pwd)/bashrc             $HOME/.bashrc
linking  $(pwd)/dosbox-0.74.conf   $HOME/.dosbox/dosbox-0.74.conf
linking  $(pwd)/feh                $HOME/.config/feh/
linking  $(pwd)/tmux.conf          $HOME/.tmux.conf
linking  $(pwd)/vimrc              $HOME/.vimrc
linking  $(pwd)/Xresources         $HOME/.Xresources

cd - > /dev/null
