#!/bin/bash


offupg()
{
    command sudo apt update
    command sudo apt full-upgrade -y
    command sudo apt autoremove -y
    command sudo apt autoclean
    command sudo shutdown -h now
}

term-title()
{
    title=$@
    command wmctrl -r :ACTIVE: -N "$title"
}

windows()
{
    command sudo grub-reboot 2
    command sudo reboot
}
