#!/bin/bash


calm-down-fans()
{
    echo 'auto' > '/sys/bus/pci/devices/0000:00:01.0/power/control'
    echo 'auto' > '/sys/bus/pci/devices/0000:01:00.0/power/control'
    echo 'error' > '/usr_tmp/fan_problem'
}

offupg()
{
    command sudo apt update
    command sudo apt full-upgrade -y
    command sudo apt autoremove -y
    command sudo apt autoclean
    command sudo shutdown -h now
}

term-title()
{
    title=$@
    command wmctrl -r :ACTIVE: -N "$title"
}

windows()
{
    command sudo grub-reboot 2
    command sudo reboot
}
