#!/bin/bash


apt() {
    case "$1" in
        purge)
            shift 1
            command sudo apt purge --auto-remove $@
            ;;
        auto)
            shift 1
            command sudo apt-mark auto $@
            ;;
        --no-rec)
            shift 1
            command apt install --no-install-recommends $@
            ;;
        reinstall)
            shift 1
            command sudo apt install --reinstall $@
            ;;
        upgrade)
            shift 1
            command sudo apt update
            command sudo apt full-upgrade
            command sudo apt autoremove -y
            command sudo apt autoclean
            ;;
        *)
            command sudo apt $@
            ;;
    esac
}

git() {
    case "$1" in
        init)
            command git init
            echo "tags" > .gitignore
            ;;
        *)
            command git $@
            ;;
    esac
}

mpv() {
    if [[ -z "$1" ]]; then
        command mpv ./
    elif [[ "$1" == "-s" ]]; then
        sub="$2"
        shift 2
        command mpv --sub-files="$sub" "$@"
    elif [[ "$1" == "-l" ]]; then
        if [ -z "$2" ]; then
            command mpv --loop-playlist ./
        else
            shift 1
            command mpv --loop-playlist "$@"
        fi
    else
        command mpv "$@"
    fi
}

mycli(){
    if [[ $1 == "-r" ]]; then
        shift 1
        command mycli -u root $@
    else
        command mycli $@
    fi
}
