" #############
" ### VIMRC ###
" #############

" "VIM is not an IDE"

" ------------------------------------------------------------------------------
" FILES
" ------------------------------------------------------------------------------

" CLIPBOARD               | $HOME/dotfiles/vim/sources/clipboard.vim
" COMMANDS                | $HOME/dotfiles/vim/sources/commands.vim
" COMPILE AND RUN         | $HOME/dotfiles/vim/sources/compile_and_run.vim
" FIXES                   | $HOME/dotfiles/vim/sources/fixes.vim
" FOLDING                 | $HOME/dotfiles/vim/sources/folding.vim
" FUNCTIONS               | $HOME/dotfiles/vim/sources/functions.vim
" HIGHLIGHTS              | $HOME/dotfiles/vim/sources/highlights.vim
" MAPPINGS                | $HOME/dotfiles/vim/sources/mappings.vim
" OPTIONS                 | $HOME/dotfiles/vim/sources/options.vim
" OTHER                   | $HOME/dotfiles/vim/sources/other.vim
" PLUGINS                 | $HOME/dotfiles/vim/sources/plugins.vim
" STATUS LINE             | $HOME/dotfiles/vim/sources/statusline.vim
" VIM DEBUGGING etc.      | $HOME/dotfiles/vim/sources/vim_debugging.vim


" ------------------------------------------------------------------------------

" Use VIM's defaults instad of VI's
set nocompatible

" Sourcing
for s:fpath in split(glob('$HOME/dotfiles/vim/sources/*.vim'), '\n')
    execute "source ".s:fpath
endfor

" Highlights needs to be sourced here
source $HOME/dotfiles/vim/sources/highlights.vim

" Fixes -- has to be sourced as last
source $HOME/dotfiles/vim/sources/fixes.vim
