" #############
" ### VIMRC ###
" #############

" VIM is not an IDE... but I still try to make it into one


" ------------------------------------------------------------------------------
" SOURCING
" ------------------------------------------------------------------------------

" Sourcing function
function! SourceDirectory(file)
  for s:fpath in split(globpath(a:file, '*.vim'), '\n')
    exe 'source' s:fpath
  endfor
endfunction

" Source directories
call SourceDirectory('$HOME/dotfiles/vim/sources')

" For some reason 'highlights.vim' doesn't source
source $HOME/dotfiles/vim/sources/highlights.vim



" ------------------------------------------------------------------------------
" SOURCE FILES
" ------------------------------------------------------------------------------

" 'set' OPTIONS        | $HOME/dotfiles/vim/sources/set_options.vim
" COMMANDS             | $HOME/dotfiles/vim/sources/commands.vim
" FUNCTIONS            | $HOME/dotfiles/vim/sources/functions.vim
" HIGHLIGHTS           | $HOME/dotfiles/vim/sources/highlights.vim
" MAPPINGS             | $HOME/dotfiles/vim/sources/mappings.vim
" OTHER                | $HOME/dotfiles/vim/sources/other.vim
" PLUGINS - LIST       | $HOME/dotfiles/vim/plugins_list.vim
" PLUGINS              | $HOME/dotfiles/vim/sources/plugins.vim
" RUN SINGLE FILE CODE | $HOME/dotfiles/vim/sources/run_single_file_code.vim
" STATUS LINE          | $HOME/dotfiles/vim/sources/statusline.vim
" SYNTAX               | $HOME/dotfiles/vim/sources/syntax_menegment.vim
