" #############
" ### VIMRC ###
" #############

" "VIM is not an IDE"... but I still try to make it into one

" Use VIM's defaults instad of VI's
set nocompatible


" ------------------------------------------------------------------------------
" FILES
" ------------------------------------------------------------------------------

" CLIPBOARD               | $HOME/dotfiles/vim/sources/clipboard.vim
" COMMANDS                | $HOME/dotfiles/vim/sources/commands.vim
" COMPILE AND RUN         | $HOME/dotfiles/vim/sources/compile_and_run.vim
" FIXES                   | $HOME/dotfiles/vim/sources/fixes.vim
" FOLDING                 | $HOME/dotfiles/vim/sources/folding.vim
" FUNCTIONS               | $HOME/dotfiles/vim/sources/functions.vim
" HIGHLIGHTS              | $HOME/dotfiles/vim/sources/highlights.vim
" MAPPINGS                | $HOME/dotfiles/vim/sources/mappings.vim
" OTHER                   | $HOME/dotfiles/vim/sources/other.vim
" PLUGINS - GENERAL       | $HOME/dotfiles/vim/sources/plugins/general.vim
" PLUGINS - LIST          | $HOME/dotfiles/vim/sources/plugins/list.vim
" PLUGINS - VARIABLES     | $HOME/dotfiles/vim/sources/plugins/variables.vim
" set OPTIONS             | $HOME/dotfiles/vim/sources/set_options.vim
" STATUS LINE             | $HOME/dotfiles/vim/sources/statusline.vim
" VIM DEBUGGING etc.      | $HOME/dotfiles/vim/sources/vim_debugging.vim


" ------------------------------------------------------------------------------
" SOURCING
" ------------------------------------------------------------------------------

" Sourcing function
function! s:SourceDirectory(dir)
    for s:fpath in split(globpath(a:dir, '*.vim'), '\n')
        execute "source ".s:fpath
    endfor
endfunction

" Source directories
call <SID>SourceDirectory('$HOME/dotfiles/vim/sources')
call <SID>SourceDirectory('$HOME/dotfiles/vim/sources/plugins')

" Highlights needs to be sourced here
source $HOME/dotfiles/vim/sources/highlights.vim

" Fixes -- has to be sourced as last
source $HOME/dotfiles/vim/sources/fixes.vim
