#!/bin/bash

wifi_ssid=$(iwgetid -r)
wifi_signal=$(awk 'NR==3 {print $4}''' /proc/net/wireless)
wifi_signal="[${wifi_signal:0:-1} dBm]"

if [ "$wifi_ssid" == "" ]; then
    wifi_ssid="[X]"
fi

echo "$wifi_ssid $wifi_signal"
