#!/bin/bash

plugged=$(ideviceinstaller -l 2> /dev/null)
if [[ $plugged == "" ]]; then
    echo "No iOS device found, is it plugged in?"
else
    echo
    echo -e "\e[4m0 | iOS\e[0m"
    echo

    i=1
    while read app
    do
        echo $i \| $( echo $app | cut -d "," -f 3 | tr -d '"')
        appid[$i]=$( echo $app | cut -d "," -f 1 )
        (( i++ ))
    done < <(ideviceinstaller -l | sed 1d)

    echo
    echo "* Type anthing else to abort *"
    echo

    read -r -p 'Choose index of app: ' option

    re='^[0-9]+$'
    if [[ $option == '0' ]]; then
        ifuse /mnt/$1
    elif [[ $option =~ $re ]] ; then
        if ! [ $option -ge $i ]; then
            ifuse --appid ${appid[$option]} /mnt/$1
        fi
    fi
fi
