#!/bin/bash

app() {
    case "$1" in
        1|electrum)
            $HOME/app/electrum/electrum & disown > /dev/null
            ;;
        2|kanjitomo)
            java -Xmx1000m -jar $HOME/app/KanjiTomo/KanjiTomo.jar -run & disown > /dev/null
            ;;
        *)
            echo "1) Electrum"
            echo "2) KanjiTomo"

            echo ""
            echo "e) Edit"
            echo "q) Quit"
            echo ""
            printf 'Choose: '
            read -r option
            if [ $option = "e" -o $option = "edit" ]; then
                edit $HOME/.bash_sources/app
            elif [ ! $option = "q" -a ! $option = "quit" ]; then
                app $option
            fi
            ;;
    esac
}
