#!/bin/bash


apt()
{
    case "$1" in
        purge)
            shift 1
            command sudo apt purge --auto-remove $@
            ;;
        auto)
            shift 1
            command sudo apt-mark auto $@
            ;;
        --no-rec)
            shift 1
            command apt install --no-install-recommends $@
            ;;
        reinstall)
            shift 1
            command sudo apt install --reinstall $@
            ;;
        upgrade)
            shift 1
            command sudo apt update
            command sudo apt full-upgrade
            command sudo apt autoremove -y
            command sudo apt autoclean
            ;;
        *)
            command sudo apt $@
            ;;
    esac
}

git-update()
{
    command git add -A
    command git commit -m "$(command date "+%F_%T")"
    command git push -u origin master
}

mpv()
{
    if [ "$1" == '' ]; then
        command mpv ./
    elif [ "$1" == "-l" ]; then
        if [ "$2" == '' ]; then
            command mpv --loop-playlist ./
        else
            shift 1
            command mpv --loop-playlist "$@"
        fi
    else
        command mpv "$@"
    fi
}
