#!/bin/bash


rm-inum()
{
    command find . -inum $1 -delete
}

windows()
{
    command sudo grub-reboot 2
    command reboot
}

offupg()
{
    command sudo apt update
    command sudo apt full-upgrade -y
    command sudo apt autoremove -y
    command sudo apt autoclean
    command sudo shutdown -h now
}

term-title()
{
    title=$@
    command wmctrl -r :ACTIVE: -N "$title"
}

install-essentials()
{
    while IFS= read -r pkg
    do
        list=$list' '$(echo $pkg| cut -f1 -d"#")
    done < "$HOME/.essential-software.list"

    command sudo apt install $list
}
