#!/bin/bash


rm-inum()
{
    command find . -inum $1 -delete
}

windows()
{
    command sudo grub-reboot 2
    command reboot
}

fuse-umnt()
{
    command fusermount -u $@
}

apt()
{
    if [ $1 == "purge" ]
    then
        shift 1
        command sudo apt purge --auto-remove $@
    elif [ $1 == "auto" ]
    then
        shift 1
        command sudo apt-mark auto $@
    elif [ $1 == "--no-rec" ]
    then
        shift 1
        command apt install --no-install-recommends $@
    elif [ $1 -- "reinstall" ]
    then
        shift 1
        command sudo apt install --reinstall $@
    elif [ $1 == "upgrade" ]
    then
        shift 1
        command sudo apt update
        command sudo apt full-upgrade
        command sudo apt autoremove -y
        command sudo apt autoclean
    else
        command sudo apt $@
    fi
}

offupg()
{
    command sudo apt update
    command sudo apt full-upgrade -y
    command sudo apt autoremove -y
    command sudo apt autoclean
    command sudo shutdown -h now
}

term-title()
{
    title=$@
    command wmctrl -r :ACTIVE: -N "$title"
}

install-essentials()
{
    while IFS= read -r pkg
    do
        list=$list' '$(echo $pkg| cut -f1 -d"#")
    done < "$HOME/.essential-software.list"

    command sudo apt install $list
}

git-update()
{
    command git add -A
    command git commit -m "$(command date "+%F_%T")"
    command git push -u origin master
}
