#!/bin/bash

game() {
    option2="y"
    case "$1" in
        1|steam)
            steam &
            ;;
        2|dosbox)
            dosbox &
            ;;
        3|minecraft)
            java -jar ~/games/Minecraft.jar &
            ;;
        4|terraria)

            ;;
        *)
            echo "1) Steam"
            echo "2) DOSbox"
            echo "3) Minecraft"
            echo "q) Canel"
            read option
            if [ ! $option = "quit" -a ! $option = "q" ]; then
                echo "Close terminal? [Y/n]"
                read option2
                game $option
            fi
            ;;
    esac
    if [ $option2 = "Y" -o $option2 = "y" ]; then
        exit
    fi
}
