#!/bin/bash


mkdir -p /tmp/vim-anywhere
file=$(mktemp -p /tmp/vim-anywhere)

xsel --clipboard --output > $file

$TERMINAL -e "vim +'Silent !wmctrl -r :ACTIVE: -b toggle,maximized_vert,maximized_horz' $file"

cat $file | xsel --clipboard --input
