#!/bin/bash

alias ap1='sudo create_ap wlo1 wlo1 x I_love_BASH' # semi open WiFi network
alias cal='LC_ALL=en_EN.utf8 ncal -Mb 2> /dev/null'
alias du='du -h'
alias git-update='command git add -A && command git commit -m "$(command date "+%F_%T")" && command git push -u origin master'
alias grep='grep --color'
alias less='less -R'
alias ll='ls -alhF --color | less -R'
alias logout="i3-msg exit"
alias ls='ls --color'
alias mkdir='mkdir -p'
alias mnt='udisksctl mount -b'
alias off='shutdown -h now'
alias op='xdg-open'
alias python='python3'
alias qmv='command qmv -v -f "do"'
alias sudo='sudo '
alias suspend='systemctl suspend'
alias umnt='udisksctl unmount -b'
alias vi='vi -p'
alias wicd='wicd-curses'
alias wine-lnk='env WINEPREFIX="$HOME/.wine" wine C:\\windows\\command\\start.exe /Unix'
