#!/bin/bash

# Auto-alias for scripts in $HOME/scripts/shell_scripts directory

# Normal scripts
for script in $HOME/scripts/shell_scripts/*; do
    if [ -f "$script" -a -x "$script" ]; then
        alias $(basename $script)="$script"
    fi
done

# Menus
for script in $HOME/scripts/shell_scripts/menus/*; do
    if [ -f "$script" -a -x "$script" ]; then
        alias $(basename $script)="$script"
    fi
done

# Scripts needing sudo
for script in $HOME/scripts/shell_scripts/sudo/*; do
    if [ -f "$script" -a -x "$script" ]; then
        alias $(basename $script)="sudo $script"
    fi
done

# Wrappers
for script in $HOME/scripts/shell_scripts/wrappers/*; do
    if [ -f "$script" -a -x "$script" ]; then
        alias $(basename $script)="$script"
    fi
done

# Launchers
for script in $HOME/scripts/shell_scripts/launchers/*; do
    if [ -f "$script" -a -x "$script" ]; then
        alias $(basename $script)="source $script"
    fi
done

# Backup tools
for script in $HOME/scripts/shell_scripts/backup_tools/*; do
    if [ -f "$script" -a -x "$script" ]; then
        alias "$(basename $script)-backup"="$script"
    fi
done
