#!/bin/bash


apt-install-from-list()
{
    for file in $@; do
        if [ -e $file ]; then
            if [[ ${file: -5} == ".list" ]]; then
                while IFS= read -r pkg; do
                    list=$list' '$(echo $pkg| cut -f1 -d"#")
                done < "$1"
                echo $list
            else
                echo "$file - file in not a list"
            fi
        else
            echo "$file - file does not exist"
        fi
    done
}

count-files()
{
    if [[ $1 == "-a" ]]; then
        ls -1a | wc -l
    else
        ls -1 | wc -l
    fi
}

offupg()
{
    command sudo apt update
    command sudo apt autoremove -y
    command sudo apt autoclean
    command sudo apt full-upgrade -y
    if hash vim 2> /dev/null; then
        vim +PlugUpgrade +PlugUpdate +qa
    fi
    command sudo shutdown -h now
}

term-title()
{
    title=$@
    command wmctrl -r :ACTIVE: -N "$title"
}

upgrade()
{
    command sudo apt update
    command sudo apt full-upgrade
    command sudo apt autoremove -y
    command sudo apt autoclean
    if hash vim 2> /dev/null; then
        vim +PlugUpgrade +PlugUpdate +qa
    fi
}

windows()
{
    command sudo grub-reboot 2
    command sudo reboot
}
