#!/bin/bash


offupg()
{
    command sudo apt update
    command sudo apt full-upgrade -y
    command sudo apt autoremove -y
    command sudo apt autoclean
    if hash vim 2> /dev/null; then
        vim +PlugUpgrade +PlugUpdate +qa
    fi
    command sudo shutdown -h now
}

term-title()
{
    title=$@
    command wmctrl -r :ACTIVE: -N "$title"
}

upgrade() {
    command sudo apt update
    command sudo apt full-upgrade
    command sudo apt autoremove -y
    command sudo apt autoclean
    if hash vim 2> /dev/null; then
        vim +PlugUpgrade +PlugUpdate +qa
    fi
}

windows()
{
    command sudo grub-reboot 2
    command sudo reboot
}
