#!/bin/bash


i3-get-window-criteria()
{
    match_int='[0-9][0-9]*'
    match_string='".*"'
    match_qstring='"[^"\\]*(\\.[^"\\]*)*"' # NOTE: Adds 1 backreference

    {
        xprop |
        sed -nr \
        -e "s/^WM_CLASS\(STRING\) = ($match_qstring), ($match_qstring)$/instance=\1\nclass=\3/p" \
        -e "s/^WM_WINDOW_ROLE\(STRING\) = ($match_qstring)$/window_role=\1/p" \
        -e "/^WM_NAME\(STRING\) = ($match_string)$/{s//title=\1/; h}" \
        -e "/^_NET_WM_NAME\(UTF8_STRING\) = ($match_qstring)$/{s//title=\1/; h}" \
        -e '${g; p}'
    } | sort | tr "\n" " " | sed -r 's/^(.*) $/[\1]\n/'
}

offupg()
{
    command sudo apt update
    command sudo apt autoremove -y
    command sudo apt autoclean
    command sudo apt full-upgrade -y
    if hash vim 2> /dev/null; then
        vim +PlugUpgrade +PlugUpdate +qa
    fi
    command sudo shutdown -h now
}

rebuild-hosts-file()
{
    set -e

    sudo echo "# Created $(command date '+%F %T') by $USER" > /tmp/hosts
    sudo echo >> /tmp/hosts

    cat $HOME/dotfiles/private/hosts/* \
    | tr A-Z a-z \
    | tr -d '\r' \
    | awk '{gsub("#.*$", ""); gsub(" *$",""); if (NF==2) {print $1 " " $2;}}' \
    | grep -v '^localhost$' \
    | sed 's/\.$//' \
    | sort -k 2\
    | uniq  \
    | sed 's/\.$//' \
    | awk '{printf("%-20s %s\n", $1, $2);}' \
    >> /tmp/hosts

    sudo mv /tmp/hosts /etc/hosts
}

umount-ios()
{
    cd
    for i in $@; do
        fusermount -u $HOME/.mount/ios$i
    done
    rmdir $HOME/.mount/* &> /dev/null
    cd - &> /dev/null
}

upgrade()
{
    command sudo apt update
    command sudo apt full-upgrade
    command sudo apt autoremove -y
    command sudo apt autoclean
    if hash vim 2> /dev/null; then
        vim +PlugUpgrade +PlugUpdate +qa
    fi
}

windows()
{
    command sudo grub-reboot 2
    command sudo reboot
}
