#!/bin/bash

# Use Vi mode
set -o vi

# Make 'less' more friendly for non-text input files
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Update Xresources
if [ -f $HOME/.Xresources ]; then
    xrdb -remove $HOME/.Xresources
    xrdb -merge $HOME/.Xresources
fi

# Update .tmux.conf on start
if [ -n $TMUX ]; then
    tmux source $HOME/.tmux.conf
fi

# Colored prompt
if [ -x /usr/bin/tput ] && tput setaf 1 &> /dev/null; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi


# ------------------------------------------------------------------------------
# COMPLETION
# ------------------------------------------------------------------------------

# Enable programmable completion features
if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
        . /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
        . /etc/bash_completion
    fi
fi

# Better autocompletion (like in zsh), but use Shift-Tab
bind '"\e[Z":menu-complete'

# Enable extended globbing
shopt -s extglob

# Magic space
bind Space:magic-space


# ------------------------------------------------------------------------------
# HISTORY
# ------------------------------------------------------------------------------

# Don't put duplicate lines or lines starting with space in the history
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE
HISTSIZE=1000
HISTFILESIZE=2000


# ------------------------------------------------------------------------------
# WINDOW
# ------------------------------------------------------------------------------

# Check the window size after each command and update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Set window title to "command | user@host:dir"
case "$TERM" in
    xterm*|rxvt*|screen*)
        PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
        ;;
    *)
        ;;
esac
