#!/bin/bash


feh() {
    if [[ $1 == "-r" ]]; then
        R="-r"
        shift 1
    fi

    if [[ -z $1 ]]; then
        command feh -B black -. $R 2> /dev/null & disown
    elif [[ ! -z $2 ]]; then
        command feh -B black -. $R "$@" & disown
    else
        file="$(readlink -f $1)"
        if [ -d "$file" ]; then
            command feh -B black -. $R "$file" 2> /dev/null & disown
        else
            dir="$(dirname "$file")"
            command feh -B black -. $R --start-at "$file" "$dir" 2> /dev/null & disown
        fi
    fi
}

find()
{
    command find $@ 2> /dev/null
}

mpv() {
    if [[ -z "$1" ]]; then
        command mpv ./
    elif [[ "$1" == "-s" ]]; then
        sub="$2"
        shift 2
        command mpv --sub-files="$sub" "$@"
    elif [[ "$1" == "-l" ]]; then
        if [ -z "$2" ]; then
            command mpv --loop-playlist ./
        else
            shift 1
            command mpv --loop-playlist "$@"
        fi
    else
        command mpv "$@"
    fi
}
