#!/bin/bash


apt() {
    case "$1" in
        --no-rec)
            shift 1
            command apt install --no-install-recommends $@
            ;;
        auto)
            shift 1
            command sudo apt-mark auto $@
            ;;
        purge)
            shift 1
            command sudo apt purge --auto-remove $@
            ;;
        reinstall)
            shift 1
            command sudo apt install --reinstall $@
            ;;
        show)
            shift 1
            command apt show $@
            ;;
        upgrade)
            shift 1
            command sudo apt update
            command sudo apt full-upgrade
            command sudo apt autoremove -y
            command sudo apt autoclean
            ;;
        *)
            command sudo apt $@
            ;;
    esac
}

find()
{
    command find $@ 2> /dev/null
}

mpv() {
    if [[ -z "$1" ]]; then
        command mpv ./
    elif [[ "$1" == "-s" ]]; then
        sub="$2"
        shift 2
        command mpv --sub-files="$sub" "$@"
    elif [[ "$1" == "-l" ]]; then
        if [ -z "$2" ]; then
            command mpv --loop-playlist ./
        else
            shift 1
            command mpv --loop-playlist "$@"
        fi
    else
        command mpv "$@"
    fi
}
