##############
### BASHRC ###
##############

#-------------------------------------------------------------------------------
# SOURCE FILES
#-------------------------------------------------------------------------------

# ALIASES   | $HOME/dotfiles/bash/sources/aliases
# APT       | $HOME/dotfiles/bash/sources/apt
# EXPORTS   | $HOME/dotfiles/bash/sources/export
# FUNCTIONS | $HOME/dotfiles/bash/sources/functions
# GENERAL   | $HOME/dotfiles/bash/sources/general
# PRIVATE   | $HOME/dotfiles/private/bash
# WRAPPERS  | $HOME/dotfiles/bash/sources/wrappers

#-------------------------------------------------------------------------------
# SOURCING
#-------------------------------------------------------------------------------

for src in $HOME/dotfiles/bash/sources/*
do
    source $src
done

source $HOME/dotfiles/private/bash
