##############
### BASHRC ###
##############

#-------------------------------------------------------------------------------
# SOURCE FILES
#-------------------------------------------------------------------------------

# ALIASES   | $HOME/dotfiles/bash/sources/aliases
# EXPORTS   | $HOME/dotfiles/bash/sources/export
# FUNCTIONS | $HOME/dotfiles/bash/sources/functions
# GENERAL   | $HOME/dotfiles/bash/sources/general
# WRAPPERS  | $HOME/dotfiles/bash/sources/wrappers

#-------------------------------------------------------------------------------
# SOURCING
#-------------------------------------------------------------------------------

for src in $HOME/dotfiles/bash/sources/*
do
    source $src
done
