##############
### BASHRC ###
##############


#-------------------------------------------------------------------------------
# SOURCE FILES
#-------------------------------------------------------------------------------

# ALIASES          | $HOME/dotfiles/bash/sources/aliases
# ALIASING SCRIPTS | $HOME/dotfiles/bash/sources/aliasing_scripts
# BINDINGS         | $HOME/dotfiles/bash/sources/bindings
# FUNCTIONS        | $HOME/dotfiles/bash/sources/functions
# MOUNTING         | $HOME/dotfiles/bash/sources/mounting
# OTHER            | $HOME/dotfiles/bash/sources/other
# PRIVATE          | $HOME/dotfiles/private/bash
# WRAPPERS         | $HOME/dotfiles/bash/sources/wrappers

#-------------------------------------------------------------------------------
# SOURCING
#-------------------------------------------------------------------------------

for src in $HOME/dotfiles/bash/sources/*
do
    source $src
done

source $HOME/dotfiles/private/bash
